# Generated by Django 5.2.4 on 2025-07-12 08:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
