# Generated by Django 5.2.4 on 2025-07-12 09:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_feedback_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
